### ISSUE TITLE
请问图片识别的时候，跨域怎么办

### ISSUE THREAD

**Issue by Mikerui** [gentwolf-shen/EasyAR-WebAR-Demo#2]
306webar.js:187 Failed to load file:///F:/%E5%89%8D%E7%AB%AF%E7%BB%83%E4%B9%A0/ar/demo1/EasyAR-WebAR-Demo-master/SimpleThreeJsExample/recognize.php: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by hanq** [comment]
自己搭建一个http服务就好啊

> only supported for protocol schemes: http, data, chrome, chrome-extension, https.
