### ISSUE TITLE
运行java main程序 Response 报错

### ISSUE THREAD

**Issue by ddean2009** [gentwolf-shen/EasyAR-WebAR-Demo#6]
我运行
backend里面java的main程序（替换了Cloud key，Cloud Secret，Client-end (Target Recognition) URL），但是运行出错， 
WebAR的Response ：

Response{protocol=http/1.1, code=500, message=Internal Server Error, url=http://**********.cn1.crs.easyar.com:8080/search}

请问下这个是什么问题？

**Comment by gentwolf-shen** [comment]
替换image为你的图片数据。
